from ubuntu:latest

ENV LIBVER=0.9.5
ENV CATVER=1.3.1

RUN apt-get update && apt-get install -y wget syslinux libyajl-dev python3 python3-dev python python-dev git zlib1g-dev libevent-pthreads-2.0-5 openjdk-8-jre netcat syslinux-utils nfs-common libssl-dev libsasl2-dev liblz4-dev libsnappy1v5 libsnappy-dev liblzo2-2 liblzo2-dev build-essential make && apt-get clean && apt-get autoremove -y


RUN wget http://archive.mapr.com/releases/v5.2.1/ubuntu/mapr-client-5.2.1.42646.GA-1.amd64.deb && dpkg -i mapr-client-5.2.1.42646.GA-1.amd64.deb && rm mapr-client-5.2.1.42646.GA-1.amd64.deb

RUN wget http://archive.mapr.com/releases/MEP/MEP-3.0/ubuntu/mapr-librdkafka_0.9.1.201703301726_all.deb && dpkg -i mapr-librdkafka_0.9.1.201703301726_all.deb && rm mapr-librdkafka_0.9.1.201703301726_all.deb

ENV HEADERDIR=/opt/mapr/include/librdkafka

ENV LD_LIBRARY_PATH=/opt/mapr/lib:$JAVA_HOME/jre/lib/amd64/server

ENV LIBVER=0.9.1

RUN wget https://github.com/edenhill/librdkafka/archive/$LIBVER.tar.gz && tar zxf $LIBVER.tar.gz && cd librdkafka-$LIBVER && ./configure && make && make install && ldconfig && cd .. && rm -rf librdkafka-$LIBVER && rm $LIBVER.tar.gz

#RUN wget https://github.com/edenhill/kafkacat/archive/$CATVER.tar.gz && tar zxf $CATVER.tar.gz && cd kafkacat-$CATVER 


#RUN ./configure --libdir=/opt/mapr/lib --includedir=/opt/mapr/include 
RUN git clone https://github.com/edenhill/kafkacat  

RUN cd kafkacat && ./configure  --enable-json

RUN cd kafkacat && make && make install && ldconfig && cd .. && rm -rf kafkacat
CMD ["/bin/bash"]
