language: c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx

script:
  ./bootstrap.sh

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq && sudo apt-get install -y libssl-dev libsasl2-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install openssl ; fi